apiVersion: apps/v1
kind: Deployment
metadata:
  name: maestro-agent-quiver
spec:
  replicas: 0
  selector:
    matchLabels:
      component: agent
      app: maestro
  template:
    metadata:
      labels:
        component: agent
        app: maestro
    spec:
      strategy:
        type: Recreate
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: nodetype
                    operator: In
                    values:
                      - maestroperf
      initContainers:
        - name: copyconfig
          image: centos:7
          command:
            - /bin/bash
            - -c
            - cp /config/* /opt/maestro/maestro-agent/config/
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: config
              mountPath: /config
            - mountPath: /opt/maestro/maestro-agent/config
              name: config-store
      containers:
        - name: worker
          image: maestroperf/maestro-agent-quiver:1.5.0-SNAPSHOT
          env:
            - name: MAESTRO_BROKER
              value: mqtt://broker
          volumeMounts:
            - mountPath: /opt/maestro/maestro-agent/config
              name: config-store
      volumes:
        - name: data
          emptyDir: {}
        - name: config-store
          emptyDir: {}
        - name: config
          configMap:
            name: agent-config
