apiVersion: v1
kind: Pod
metadata:
  name: maestro-client
spec:
  restartPolicy: Never
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: nodetype
                operator: In
                values:
                  - maestroperf
  containers:
    - name: idle
      image: centos:7
      command:
        - /bin/bash
        - -c
        - sleep 1800
      volumeMounts:
        - mountPath: /maestro
          name: data
    - name: client
      image: maestroperf/maestro-client:1.5.0-SNAPSHOT
      command:
        - /bin/bash
        - -c
        - /opt/maestro/maestro-cli/bin/maestro-cli exec -s ${TEST_CASE}
      env:
        - name: MAESTRO_BROKER
          value: mqtt://broker
        - name: SEND_RECEIVE_URL
          valueFrom:
            configMapKeyRef:
              name: client-config
              key: sendReceiveUrl
        - name: TEST_DURATION
          valueFrom:
            configMapKeyRef:
              name: client-config
              key: testDuration
              optional: true
        - name: TEST_CASE
          valueFrom:
            configMapKeyRef:
              name: client-config
              key: testCase
        - name: TEST_PARAMS
          valueFrom:
            configMapKeyRef:
              name: client-config
              key: testParams
              optional: true
        - name: SOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: client-config
              key: sourceUrl
        - name: SOURCE_BRANCH
          valueFrom:
            configMapKeyRef:
              name: client-config
              key: sourceBranch
      volumeMounts:
        - mountPath: /opt/maestro/maestro-cli/scripts
          name: config
        - mountPath: /maestro
          name: data
        - mountPath: /test-scripts
          name: test-scripts
  volumes:
    - name: config
      configMap:
        name: client-config
    - name: test-scripts
      configMap:
        name: test-scripts
    - name: data
      inmemory: {}
