version: '3.4'
networks:
    cluster:
      driver: bridge
    test:
      driver: bridge
services:
  broker:
    image: maestroperf/maestro-broker:1.5.0-SNAPSHOT
    networks:
    - cluster
    ports:
    - "18161:8161"
    - "1884:1883"
  sut:
    build: suts/apache-artemis
    networks:
    - test
    ports:
    - "5672:5672"
    - "8161:8161"
    - "61613:61613"
    - "61616:61616"
  worker:
    image: maestroperf/maestro-worker:1.5.0-SNAPSHOT
    networks:
      - cluster
      - test
    depends_on:
      - broker
      - sut
  inspector:
      image: maestroperf/maestro-inspector:1.5.0-SNAPSHOT
      ports:
        - "38000:8000"
      networks:
        - cluster
        - test
      depends_on:
        - sut
        - broker
  client:
      image: maestroperf/maestro-client:1.5.0-SNAPSHOT
      networks:
        - cluster
      ports:
        - "8000:8000"
      depends_on:
        - worker
        - broker
  reports:
    image: maestroperf/maestro-reports:1.5.0-SNAPSHOT
    networks:
      - cluster
    ports:
      - "6500:6500"
    volumes:
      - reports:/maestro
    depends_on:
      - broker
  agent-quiver:
    build:
      context: agent-quiver
      args:
      - MAESTRO_VERSION=1.5.0-SNAPSHOT
      target: maestro-agent-quiver
    ports:
    - "48000:8000"
    networks:
    - cluster
    - test
    depends_on:
    - broker

volumes:
  reports:

